//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaning_company_ArapovDaniil.ModelBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesADV : DbContext
    {
        public EntitiesADV()
            : base("name=EntitiesADV")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bucket> Bucket { get; set; }
        public virtual DbSet<ClearingAgent> ClearingAgent { get; set; }
        public virtual DbSet<Client_C> Client_C { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<PackageCommit> PackageCommit { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiseImage> ServiseImage { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeClearingAgent> TypeClearingAgent { get; set; }
        public virtual DbSet<TypePackage> TypePackage { get; set; }
        public virtual DbSet<TypeService> TypeService { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
