//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaning_company_ArapovDaniil.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageCommit
    {
        public int ID { get; set; }
        public int PackageID { get; set; }
        public string Text { get; set; }
        public int ClientID { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Client_C Client_C { get; set; }
        public virtual Package Package { get; set; }
    }
}
